export interface SeedGame {
  name: string;
  steamAppId?: string;
  genres?: string;
  tags?: string;
  isMultiplayer?: boolean;
  isCoop?: boolean;
  releaseYear?: number;
  umbStatus?: string;
  agsStatus?: string;
  umbHours?: number;
  agsHours?: number;
  agsHidden?: boolean;
}

export const seedGames: SeedGame[] = [
  {
    name: "MORDHAU",
    steamAppId: "629760",
    genres: "Экшен, Инди",
    tags: "PvP, Средневековье, Ближний бой, Мультиплеер",
    isMultiplayer: true,
    isCoop: false,
    releaseYear: 2019,
    umbStatus: "bored",
    agsStatus: "bored",
    umbHours: 3717,
    agsHours: 2523,
  },
  {
    name: "Valheim",
    steamAppId: "892970",
    genres: "Экшен, Приключения, RPG",
    tags: "Выживание, Открытый мир, Кооп, Викинги",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2021,
    umbStatus: "bored",
    agsStatus: "played",
    umbHours: 1047,
    agsHours: 614,
  },
  {
    name: "Baldur's Gate 3",
    steamAppId: "1086940",
    genres: "RPG, Приключения, Стратегия",
    tags: "RPG, Кооп, Сюжет, Пошаговая",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2023,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 486,
    agsHours: 309,
  },
  {
    name: "Mount & Blade II: Bannerlord",
    steamAppId: "261550",
    genres: "Экшен, RPG, Стратегия",
    tags: "Средневековье, Открытый мир, Песочница",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2022,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 140,
    agsHours: 1260,
  },
  {
    name: "V Rising",
    steamAppId: "1604030",
    genres: "Экшен, Приключения",
    tags: "Выживание, Открытый мир, Вампиры, Кооп",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2024,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 47,
    agsHours: 70,
  },
  {
    name: "Deep Rock Galactic",
    steamAppId: "548430",
    genres: "Экшен, Шутер",
    tags: "Кооп, Шутер, Научная фантастика",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2020,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 63,
    agsHours: 8,
  },
  {
    name: "Tom Clancy's Rainbow Six Siege",
    steamAppId: "359550",
    genres: "Экшен, Шутер",
    tags: "Тактика, Мультиплеер, Соревновательная",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2015,
    umbStatus: "dropped",
    agsStatus: "played",
    umbHours: 65,
    agsHours: 228,
  },
  {
    name: "Rust",
    steamAppId: "252490",
    genres: "Экшен, Приключения, Инди",
    tags: "Выживание, Открытый мир, PvP, Мультиплеер",
    isMultiplayer: true,
    isCoop: false,
    releaseYear: 2018,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 387,
    agsHours: 38,
  },
  {
    name: "Factorio",
    steamAppId: "427520",
    genres: "Симулятор, Стратегия",
    tags: "Автоматизация, Строительство, Кооп",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2020,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 271,
    agsHours: 40,
  },
  {
    name: "Kingdom Come: Deliverance",
    steamAppId: "379430",
    genres: "Экшен, Приключения, RPG",
    tags: "Средневековье, Открытый мир, Реализм",
    isMultiplayer: false,
    isCoop: false,
    releaseYear: 2018,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 149,
    agsHours: 36,
  },
  {
    name: "Kingdom Come: Deliverance II",
    steamAppId: "1771300",
    genres: "Экшен, Приключения, RPG",
    tags: "Средневековье, Открытый мир, Реализм",
    isMultiplayer: false,
    isCoop: false,
    releaseYear: 2025,
    umbStatus: "playing",
    agsStatus: "playing",
    umbHours: 9,
    agsHours: 146,
  },
  {
    name: "Battlefield 1",
    steamAppId: "1238840",
    genres: "Экшен, Шутер",
    tags: "Первая мировая, Мультиплеер, Шутер",
    isMultiplayer: true,
    isCoop: false,
    releaseYear: 2016,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 141,
    agsHours: 9,
  },
  {
    name: "The Riftbreaker",
    steamAppId: "780310",
    genres: "Экшен, RPG, Стратегия",
    tags: "Строительство, Выживание, Хак-н-слэш",
    isMultiplayer: false,
    isCoop: false,
    releaseYear: 2021,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 22,
    agsHours: 14,
  },
  {
    name: "Deadzone: Rogue",
    steamAppId: "3228590",
    genres: "Экшен, RPG",
    tags: "Рогалик, Шутер, Экстракшн",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2024,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 20,
    agsHours: 13,
  },
  {
    name: "Ведьмак 3: Дикая Охота",
    steamAppId: "292030",
    genres: "RPG, Приключения",
    tags: "Открытый мир, Сюжет, Фэнтези",
    isMultiplayer: false,
    isCoop: false,
    releaseYear: 2015,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 13,
    agsHours: 77,
  },
  {
    name: "Dying Light",
    steamAppId: "239140",
    genres: "Экшен, RPG",
    tags: "Зомби, Открытый мир, Кооп, Паркур",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2015,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 13,
    agsHours: 110,
  },
  {
    name: "theHunter: Call of the Wild",
    steamAppId: "518790",
    genres: "Приключения, Симулятор",
    tags: "Охота, Открытый мир, Кооп, Природа",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2017,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 6,
    agsHours: 9,
  },
  {
    name: "Ready or Not",
    steamAppId: "1144200",
    genres: "Экшен, Шутер",
    tags: "Тактика, Кооп, SWAT, Реализм",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2023,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 5,
    agsHours: 2,
  },
  {
    name: "7 Days to Die",
    steamAppId: "251570",
    genres: "Экшен, Приключения, RPG",
    tags: "Зомби, Выживание, Кооп, Открытый мир",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2024,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 4,
    agsHours: 5,
  },
  {
    name: "Icarus",
    steamAppId: "1149460",
    genres: "Экшен, Приключения",
    tags: "Выживание, Кооп, Открытый мир, Крафт",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2021,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 3,
    agsHours: 3,
  },
  {
    name: "Sons Of The Forest",
    steamAppId: "1326470",
    genres: "Экшен, Приключения",
    tags: "Выживание, Хоррор, Кооп, Открытый мир",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2024,
    umbStatus: "dropped",
    agsStatus: "played",
    umbHours: 0,
    agsHours: 52,
  },
  {
    name: "Foundation",
    steamAppId: "690830",
    genres: "Симулятор, Стратегия",
    tags: "Градострой, Средневековье, Менеджмент",
    isMultiplayer: false,
    isCoop: false,
    releaseYear: 2024,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 2,
    agsHours: 20,
  },
  {
    name: "Warhammer: Vermintide 2",
    steamAppId: "552500",
    genres: "Экшен",
    tags: "Кооп, Хак-н-слэш, Шутер, Фэнтези",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2018,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 1,
    agsHours: 112,
  },
  {
    name: "HELLDIVERS 2",
    steamAppId: "553850",
    genres: "Экшен",
    tags: "Кооп, Шутер, Научная фантастика",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2024,
    umbStatus: undefined,
    agsStatus: "played",
    umbHours: 0,
    agsHours: 53,
  },
  {
    name: "Crusader Kings III",
    steamAppId: "1158310",
    genres: "RPG, Симулятор, Стратегия",
    tags: "Гранд-стратегия, Средневековье, Песочница",
    isMultiplayer: true,
    isCoop: false,
    releaseYear: 2020,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 3,
    agsHours: 153,
  },
  {
    name: "Bellwright",
    steamAppId: "1580830",
    genres: "Экшен, RPG, Стратегия",
    tags: "Средневековье, Открытый мир, Колония, Кооп",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2024,
    umbStatus: "dropped",
    agsStatus: "dropped",
    umbHours: 1,
    agsHours: 1,
  },
  {
    name: "Satisfactory",
    steamAppId: "526870",
    genres: "Приключения, Симулятор, Стратегия",
    tags: "Автоматизация, Строительство, Кооп, Фабрика",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2024,
    umbStatus: "dropped",
    agsStatus: "dropped",
    umbHours: 4,
    agsHours: 1,
  },
  {
    name: "Barotrauma",
    steamAppId: "602960",
    genres: "Экшен, Инди, RPG, Симулятор",
    tags: "Кооп, Выживание, Подлодка, Научная фантастика",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2023,
    umbStatus: "dropped",
    agsStatus: "played",
    umbHours: 0,
    agsHours: 13,
  },
  {
    name: "PAYDAY 2",
    steamAppId: "218620",
    genres: "Экшен, RPG",
    tags: "Кооп, Шутер, Ограбления, Стелс",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2013,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 0.5,
    agsHours: 211,
  },
  {
    name: "Destiny 2",
    steamAppId: "1085660",
    genres: "Экшен, Шутер",
    tags: "Шутер, Лутер-шутер, Научная фантастика, MMO, Кооп",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2019,
    umbStatus: "dropped",
    agsStatus: "bored",
    umbHours: 0,
    agsHours: 1832,
  },
  {
    name: "Divinity: Original Sin 2",
    steamAppId: "435150",
    genres: "RPG, Приключения, Стратегия",
    tags: "RPG, Кооп, Пошаговая, Фэнтези",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2017,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 565,
    agsHours: 6,
  },
  {
    name: "Abiotic Factor",
    steamAppId: "427410",
    genres: "Экшен, Приключения, RPG",
    tags: "Выживание, Кооп, Научная фантастика, Крафт",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2024,
    umbStatus: "wishlist",
    agsStatus: undefined,
    umbHours: 0,
    agsHours: 0,
  },
  {
    name: "Far Far West",
    steamAppId: "3124540",
    genres: "Экшен, RPG",
    tags: "Вестерн, Кооп, Открытый мир, Выживание",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2025,
    umbStatus: "wishlist",
    agsStatus: undefined,
    umbHours: 0,
    agsHours: 0,
  },
  {
    name: "RoboQuest",
    steamAppId: "692890",
    genres: "Экшен, Инди",
    tags: "Шутер, Рогалик, Кооп, Роботы",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2023,
    umbStatus: "wishlist",
    agsStatus: undefined,
    umbHours: 0,
    agsHours: 0,
  },
  {
    name: "Terraria",
    steamAppId: "105600",
    genres: "Экшен, Приключения, Инди",
    tags: "Песочница, Выживание, 2D, Крафт",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2011,
    umbStatus: "played",
    agsStatus: "played",
    umbHours: 2,
    agsHours: 4,
    agsHidden: true,
  },
  {
    name: "Raft",
    steamAppId: "648800",
    genres: "Приключения, Инди",
    tags: "Выживание, Кооп, Крафт, Открытый мир",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2022,
    umbStatus: "dropped",
    agsStatus: "dropped",
    umbHours: 0,
    agsHours: 0,
    agsHidden: true,
  },
  {
    name: "Palworld",
    steamAppId: "1623730",
    genres: "Экшен, Приключения, RPG",
    tags: "Выживание, Открытый мир, Кооп, Существа",
    isMultiplayer: true,
    isCoop: true,
    releaseYear: 2024,
    umbStatus: "dropped",
    agsStatus: "dropped",
    umbHours: 0,
    agsHours: 0,
    agsHidden: true,
  },
];

// Expanded recommendations - all text in Russian
export const seedRecommendations = [
  // === TOP TIER (90+) ===
  {
    name: "Enshrouded",
    steamAppId: "1203620",
    reason: "Кооп survival RPG, похож на Valheim, но в фэнтези сеттинге. Реалистичная графика, строительство, прокачка.",
    genres: "Экшен, RPG, Приключения",
    tags: "Выживание, Кооп, Открытый мир, Крафт, RPG",
    score: 95,
  },
  {
    name: "Remnant 2",
    steamAppId: "1282100",
    reason: "Кооп-шутер с RPG элементами и Souls-like боёвкой. Напоминает Destiny 2 по стилю. Рандомные уровни, лут, боссы.",
    genres: "Экшен, RPG",
    tags: "Кооп, Souls-like, Шутер, Лутер, От третьего лица",
    score: 94,
  },
  {
    name: "Conan Exiles",
    steamAppId: "440900",
    reason: "Survival с PvP и кооп, строительство баз, реалистичная графика. Близок к Valheim и Rust по духу.",
    genres: "Экшен, Приключения, RPG",
    tags: "Выживание, Открытый мир, Кооп, PvP, Строительство",
    score: 93,
  },
  {
    name: "Hunt: Showdown 1896",
    steamAppId: "594650",
    reason: "Тактический PvPvE шутер, атмосферный и хардкорный. Перекрёсток PvP и кооп.",
    genres: "Экшен, Шутер",
    tags: "PvP, PvE, Хоррор, Тактика, Кооп, Экстракшн",
    score: 92,
  },
  {
    name: "Warhammer 40,000: Darktide",
    steamAppId: "1361210",
    reason: "Кооп-шутер от создателей Vermintide 2. АГС любил Vermintide — это его наследник в мире Warhammer 40K.",
    genres: "Экшен",
    tags: "Кооп, Шутер, Warhammer, Хак-н-слэш, Научная фантастика",
    score: 91,
  },
  {
    name: "Escape from Tarkov",
    steamAppId: "3932890",
    reason: "Хардкорный тактический шутер с лутом и экстракшном. Идеален для AGS (опыт Destiny 2) и UMB.",
    genres: "Экшен, Шутер, RPG",
    tags: "Тактика, Шутер, Выживание, Хардкор, PvP, Экстракшн",
    score: 90,
  },
  {
    name: "Chivalry 2",
    steamAppId: "1824220",
    reason: "Средневековый PvP слэшер, прямой конкурент MORDHAU. Свежая альтернатива для ветеранов.",
    genres: "Экшен",
    tags: "Средневековье, PvP, Ближний бой, Мультиплеер",
    score: 90,
  },
  // === HIGH TIER (80-89) ===
  {
    name: "Arc Raiders",
    steamAppId: "1808500",
    reason: "PvPvE шутер-экстракшн от создателей Battlefield. Мощная графика, тактические бои с ИИ и игроками.",
    genres: "Экшен, Шутер",
    tags: "PvPvE, Экстракшн, Кооп, Научная фантастика, Шутер",
    score: 89,
  },
  {
    name: "Warframe",
    steamAppId: "230410",
    reason: "Бесплатный кооп лутер-шутер. Отличная альтернатива Destiny 2 для АГС. Тонны контента.",
    genres: "Экшен, Шутер",
    tags: "Кооп, Лутер-шутер, Научная фантастика, Бесплатная, Ниндзя",
    score: 88,
  },
  {
    name: "Elden Ring",
    steamAppId: "1245620",
    reason: "Огромный открытый мир, RPG, есть кооп. Потрясающий дизайн мира от FromSoftware.",
    genres: "Экшен, RPG",
    tags: "Souls-like, Открытый мир, Кооп, Фэнтези",
    score: 87,
  },
  {
    name: "Monster Hunter Wilds",
    steamAppId: "2246340",
    reason: "Кооп-охота на монстров, глубокая боевая система. Реалистичная графика нового поколения.",
    genres: "Экшен, RPG",
    tags: "Кооп, Охота, Открытый мир, RPG, Боссы",
    score: 87,
  },
  {
    name: "Outward",
    steamAppId: "794260",
    reason: "Кооп RPG с выживанием, хардкорная боёвка. Похоже на KCD + survival.",
    genres: "RPG, Приключения",
    tags: "Кооп, Открытый мир, Выживание, RPG, Фэнтези",
    score: 86,
  },
  {
    name: "Dark and Darker",
    steamAppId: "2016590",
    reason: "PvPvE экстракшн в фэнтези подземельях. Средневековая атмосфера, лут и хардкор.",
    genres: "Экшен, RPG",
    tags: "PvPvE, Экстракшн, Фэнтези, Подземелья, Кооп",
    score: 85,
  },
  {
    name: "Myth of Empires",
    steamAppId: "1371580",
    reason: "Sandbox survival MMO, похож на Bannerlord + Rust. Средневековый сеттинг, строительство замков.",
    genres: "Экшен, Приключения, RPG",
    tags: "Выживание, Открытый мир, Средневековье, PvP, Песочница, MMO",
    score: 85,
  },
  {
    name: "The Forest",
    steamAppId: "242760",
    reason: "Кооп-хоррор-survival. Отличная атмосфера, реалистичная графика. Предшественник Sons of the Forest.",
    genres: "Экшен, Приключения, Инди",
    tags: "Выживание, Хоррор, Кооп, Открытый мир",
    score: 84,
  },
  {
    name: "Dune: Awakening",
    steamAppId: "1172710",
    reason: "MMO survival во вселенной Дюны от создателей Conan Exiles. Графика нового поколения, PvP и кооп.",
    genres: "Экшен, RPG, Приключения",
    tags: "Выживание, MMO, Открытый мир, PvP, Кооп, Научная фантастика",
    score: 84,
  },
  {
    name: "Green Hell",
    steamAppId: "815370",
    reason: "Реалистичный survival в джунглях Амазонки с кооп. Глубокие механики крафта и медицины.",
    genres: "Экшен, Приключения, Симулятор",
    tags: "Выживание, Кооп, Открытый мир, Реализм, Крафт",
    score: 83,
  },
  {
    name: "GTFO",
    steamAppId: "493520",
    reason: "Хардкорный кооп-хоррор-шутер. Требует командной работы и тактики на каждом шагу.",
    genres: "Экшен, Шутер",
    tags: "Кооп, Хоррор, Шутер, Тактика, Хардкор",
    score: 82,
  },
  {
    name: "DayZ",
    steamAppId: "221100",
    reason: "Хардкорный survival с PvP. Реалистичный мир, атмосферный. Для тех, кому Rust понравился.",
    genres: "Экшен, Приключения",
    tags: "Выживание, Открытый мир, PvP, Мультиплеер, Зомби",
    score: 81,
  },
  {
    name: "Once Human",
    steamAppId: "2139460",
    reason: "Бесплатный кооп survival, открытый мир. Свежий, интересный пост-апокалиптический сеттинг.",
    genres: "Экшен, Приключения, RPG",
    tags: "Выживание, Кооп, Открытый мир, Шутер, Бесплатная",
    score: 81,
  },
  {
    name: "Soulmask",
    steamAppId: "2646460",
    reason: "Новый survival с крафтом и NPC-компаньонами. Красивая графика, глубокие системы.",
    genres: "Экшен, Приключения, RPG",
    tags: "Выживание, Открытый мир, Кооп, Крафт, Строительство",
    score: 80,
  },
  // === MID-HIGH TIER (70-79) ===
  {
    name: "Project Zomboid",
    steamAppId: "108600",
    reason: "Глубокий survival с зомби, кооп мультиплеер. Очень затягивающий, масса механик.",
    genres: "RPG, Симулятор",
    tags: "Выживание, Зомби, Кооп, Песочница, Строительство",
    score: 79,
  },
  {
    name: "No Man's Sky",
    steamAppId: "275850",
    reason: "Огромный кооп-мир, исследования, строительство баз. Тонны контента и обновлений.",
    genres: "Экшен, Приключения",
    tags: "Кооп, Открытый мир, Выживание, Исследования, Космос",
    score: 78,
  },
  {
    name: "Lethal Company",
    steamAppId: "1966720",
    reason: "Кооп-хоррор, очень популярный. Отличная для 2+ игроков, весело и страшно одновременно.",
    genres: "Экшен, Хоррор",
    tags: "Кооп, Хоррор, Мультиплеер, Инди, Научная фантастика",
    score: 78,
  },
  {
    name: "R.E.P.O.",
    steamAppId: "3241660",
    reason: "Новый хит кооп-хоррора 2025. Физика объектов, командная работа, уникальные механики.",
    genres: "Экшен, Хоррор",
    tags: "Кооп, Хоррор, Физика, Мультиплеер, Инди",
    score: 78,
  },
  {
    name: "Starship Troopers: Extermination",
    steamAppId: "1268750",
    reason: "Кооп-шутер на 16 игроков, строительство баз. Как Helldivers, но от первого лица.",
    genres: "Экшен, Шутер",
    tags: "Кооп, Шутер, Научная фантастика, Строительство",
    score: 77,
  },
  {
    name: "Insurgency: Sandstorm",
    steamAppId: "581320",
    reason: "Реалистичный тактический шутер с кооп-режимами. Для любителей тактики и реализма.",
    genres: "Экшен, Шутер",
    tags: "Тактика, Шутер, Кооп, Мультиплеер, Реализм",
    score: 76,
  },
  {
    name: "Back 4 Blood",
    steamAppId: "924970",
    reason: "Кооп-шутер с зомби, наследник Left 4 Dead. UMB играл в L4D2.",
    genres: "Экшен, Шутер",
    tags: "Кооп, Зомби, Шутер, Мультиплеер",
    score: 75,
  },
  {
    name: "Arma 3",
    steamAppId: "107410",
    reason: "Реалистичный военный симулятор с кооп-миссиями. Для любителей тактики и реализма.",
    genres: "Экшен, Симулятор, Стратегия",
    tags: "Военный, Тактика, Кооп, Симулятор, Песочница",
    score: 75,
  },
  {
    name: "Squad",
    steamAppId: "393380",
    reason: "Тактический шутер, большие карты, командная игра. Очень реалистичный.",
    genres: "Экшен, Шутер",
    tags: "Тактика, Шутер, Мультиплеер, Военный, Реализм",
    score: 74,
  },
  {
    name: "Hell Let Loose",
    steamAppId: "686810",
    reason: "Реалистичный WW2 шутер 50v50. Стоит попробовать вместе. UMB пробовал немного.",
    genres: "Экшен, Шутер, Симулятор",
    tags: "Шутер, Вторая мировая, Мультиплеер, Тактика, Реализм",
    score: 74,
  },
  {
    name: "Enlisted",
    steamAppId: "2051620",
    reason: "Бесплатный WW2 шутер с отрядами. Уникальная механика управления сквадом. Для любителей Battlefield.",
    genres: "Экшен, Шутер",
    tags: "Шутер, Вторая мировая, Мультиплеер, Бесплатная",
    score: 73,
  },
  {
    name: "Nightingale",
    steamAppId: "1928980",
    reason: "Кооп survival RPG от бывших разработчиков BioWare. Крафт, строительство, магия.",
    genres: "Экшен, RPG, Приключения",
    tags: "Выживание, Кооп, Открытый мир, Крафт, Фэнтези",
    score: 73,
  },
  {
    name: "Total War: WARHAMMER III",
    steamAppId: "1142710",
    reason: "АГС наиграл 187ч. Гранд-стратегия + тактические бои. Есть кооп кампания.",
    genres: "Стратегия",
    tags: "Гранд-стратегия, Warhammer, Кооп, RTS, Фэнтези",
    score: 72,
  },
  {
    name: "Space Engineers",
    steamAppId: "244850",
    reason: "Кооп-песочница в космосе. Строительство кораблей и станций. Инженерный подход.",
    genres: "Экшен, Инди, Симулятор",
    tags: "Космос, Песочница, Кооп, Строительство, Выживание",
    score: 72,
  },
  {
    name: "Manor Lords",
    steamAppId: "1363080",
    reason: "Средневековый градострой с тактическими боями. Оба интересуетесь средневековьем.",
    genres: "Стратегия, Симулятор",
    tags: "Средневековье, Градострой, Стратегия, Менеджмент",
    score: 71,
  },
  {
    name: "Split Fiction",
    steamAppId: "2929890",
    reason: "Кооп-приключение от создателей It Takes Two. Каждый уровень — новая механика. Нужна только 1 копия!",
    genres: "Приключения, Экшен",
    tags: "Кооп, Приключения, Сюжет, Инди",
    score: 71,
  },
  {
    name: "PEAK",
    steamAppId: "2933960",
    reason: "Кооп-рогалик про восхождение на гору. Хит 2025 года, 10 млн продаж. Весело и напряжённо.",
    genres: "Экшен, Приключения",
    tags: "Кооп, Рогалик, Мультиплеер, Инди",
    score: 70,
  },
  {
    name: "Grounded",
    steamAppId: "962130",
    reason: "Кооп-выживание от Obsidian. Уникальная концепция — вы уменьшены до размера муравья.",
    genres: "Экшен, Приключения",
    tags: "Выживание, Кооп, Открытый мир, Строительство",
    score: 70,
  },
  {
    name: "Tribes of Midgard",
    steamAppId: "858820",
    reason: "Viking-тематика как Valheim, но с roguelite элементами. Кооп до 10 игроков.",
    genres: "Экшен, RPG",
    tags: "Кооп, Выживание, Викинги, Рогалик, Экшен RPG",
    score: 69,
  },
  // === EXTRA (60-69) ===
  {
    name: "Vintage Story",
    steamAppId: "1527950",
    reason: "Реалистичный survival-крафт. Глубочайшие системы выживания. Медленный, но затягивающий.",
    genres: "Симулятор, Инди",
    tags: "Выживание, Крафт, Кооп, Песочница, Реализм",
    score: 68,
  },
  {
    name: "No Rest for the Wicked",
    steamAppId: "1610570",
    reason: "Экшен-RPG от создателей Ori. Красивая графика, глубокая боёвка. Есть кооп.",
    genres: "Экшен, RPG",
    tags: "Кооп, Экшен RPG, Фэнтези, Souls-like",
    score: 68,
  },
  {
    name: "Empyrion - Galactic Survival",
    steamAppId: "383120",
    reason: "Космический survival + строительство. Кооп, огромный мир, строительство кораблей.",
    genres: "Экшен, Приключения, Симулятор",
    tags: "Космос, Выживание, Кооп, Открытый мир, Строительство",
    score: 67,
  },
  {
    name: "Ravenswatch",
    steamAppId: "2071280",
    reason: "Кооп action roguelite, тёмная сказочная тематика. До 4 игроков.",
    genres: "Экшен, RPG",
    tags: "Кооп, Рогалик, Экшен RPG, Фэнтези",
    score: 66,
  },
  {
    name: "Century: Age of Ashes",
    steamAppId: "918570",
    reason: "PvP на драконах, бесплатная. Для любителей PvP с новой механикой полёта.",
    genres: "Экшен",
    tags: "PvP, Драконы, Бесплатная, Мультиплеер, Фэнтези",
    score: 63,
  },
  {
    name: "Borderlands 3",
    steamAppId: "397540",
    reason: "Кооп лутер-шутер с юмором. Тонны оружия, кооп кампания на двоих.",
    genres: "Экшен, RPG, Шутер",
    tags: "Кооп, Лутер-шутер, Открытый мир, Юмор",
    score: 65,
  },
  {
    name: "Phasmophobia",
    steamAppId: "739630",
    reason: "Кооп-хоррор про охоту на призраков. 25 млн проданных копий. Уникальный опыт.",
    genres: "Экшен, Инди",
    tags: "Кооп, Хоррор, Призраки, Мультиплеер",
    score: 72,
  },
  {
    name: "Warhaven",
    steamAppId: "2107940",
    reason: "PvP средневековые бои с магией. Альтернатива MORDHAU с фэнтези элементами.",
    genres: "Экшен",
    tags: "PvP, Средневековье, Ближний бой, Фэнтези, Мультиплеер",
    score: 63,
  },
  {
    name: "Baldur's Gate 3 (новое прохождение)",
    steamAppId: "1086940",
    reason: "Переиграть с другим классом? Оба наиграли много, но с новыми решениями всё может быть свежо.",
    genres: "RPG, Приключения, Стратегия",
    tags: "RPG, Кооп, Сюжет, Пошаговая",
    score: 60,
  },
  {
    name: "Elden Ring: Nightreign",
    steamAppId: "2958550",
    reason: "Новый кооп-рогалик от FromSoftware во вселенной Elden Ring. Специально разработан для кооп.",
    genres: "Экшен, RPG",
    tags: "Кооп, Souls-like, Рогалик, Фэнтези, Открытый мир",
    score: 89,
  },
];
